### PR TITLE
New descriptions

### PR DESCRIPTION
**Pull request by FeatherAntennae**
P.R. to help keep track of the descriptions I add, and to facilitate reviews and feedback.

Considering this done and ready to merge (unless anything should be changed first).

Will do a new pull request when I have some more time for contributions. 

## Done
- **objects/alpaca**
  - [x] Add Thaumoth description to existing ".patch"
  - [x] Add Saturnian description for missing base game object.
  - [x] Add Thaumoth description for missing base game object.
- **objects/avian**
  - [x] Add Thaumoth description to existing ".patch"
- **objects/crafting**
  - [x] Cooking station
  - [x] Mech station
  - [x] Old crafting station (barely used in-game)
  - [x] All tiers of every upgradable crafting stations in the base game.
  - [x] Fossil station
  - [x] All two levels of the normal (non-saturnian) loom.

### CODE REVIEW

**Review by CyanSkyKnight — COMMENTED** [review]
These are great! The only change I'd suggest is for Thaumoths to call themselves Thaumoths instead of Saturnians. They are different names for the same species, but Thaumoths prefer their older species name.

**Comment by FeatherAntennae** [comment]
Noted! I'll change that later today.

**Comment by FeatherAntennae** [comment]
Noted! I'll change that later today. ^^

**Comment by FeatherAntennae** [comment]
@CyanSkyKnight I've done some descriptions for each tier of every upgradeable crafting stations from the base game. I'd like some feedback on them, especially the "crafting anvil" one since its upgrades and addons include some weapons and armors touching the lore, so I tried to reference them as well as I could.

**Comment by CyanSkyKnight** [comment]
Yeah, that's pretty good!
The only thing I'd change is the Saturnians' description for the Separator addon.
The Saturnians that use melee weapons mostly use magical rapiers and maces.

**Comment by FeatherAntennae** [comment]
> Yeah, that's pretty good! The only thing I'd change is the Saturnians' description for the Separator addon. The Saturnians that use melee weapons mostly use magical rapiers and maces.

Was a bit busy with the end of the semester, sorry for the delay.

Just to make sure I change the right thing, I wanted to validate with you first.

The **separator add-on** has the following descriptions:
- **Saturnian:** I've heard the moon guards of Actias use weapons and armors similar to what this addon can produce.
- **Thaumoth:** This allows the replicator to conjure the legendary armors and scythes used by the royal guards of Actias.

Should I change the Saturnian one?

Or did you mean the **replicator (3rd level anvil, no add-on)** description:
- **Saturnian:** A replicator! It can make some very powerful bows, scythes, maces, and rapiers.
- **Thaumoth:** With the right addons, this replicator could make weapons to match the strongest mages of Actias.

**Comment by CyanSkyKnight** [comment]
Yeah, it's the Saturnian description for the Separator.

**Pull request merged**
